language: node_js
node_js:
  - "6"
services:
  - docker
install:
  - docker pull kenfehling/node6:latest
  - npm install
  - cd server; npm install; npm run build; cd ..
script:
  - docker run --name dc kenfehling/node6:latest &
  - sleep 5
  - docker cp server/ dc:/opt
  - docker exec -it dc "cd /opt/server; npm test"