language: node_js
node_js:
- '6'
script:
- npm run lint
- npm test
- npm run build
deploy:
  local_dir: server/build
  provider: elasticbeanstalk
  bucket_name: kenfehling
  access_key_id: AKIAIJLANAWI5VK7AV3Q
  secret_access_key:
    secure: 1cG/I8Gq0IarOV0X9XfTzVK8S5cIvrkPII4Hn0/wpd6WPDQS3hF10o0xMm3BmUR5u4caugRT+5s4Q//NMO5wFmFafvLnw28egMFT2X7sQKFYKIDLNbJLidZhLaNPAeOgk+GT/lJXpzq+KcH1IMCR2sf9s8L+KBhk1kbi+RfP21jnmmb/qOvt47puZs4ZjawFy21GOYD0VQW8QxR+9A6A/Jn1y09eGaVtkaS7p8J82Pyy0WHViSr2iy/wGCWSWVgf6pagWgUjpK26Ci/EbQa9+zNgGsvACIZVGMllJawn1k67XJuB+bg/1Bziy1jU6j/l6tZy2q2k+eXSvOrCfOtxoLISHPLDzr8GWgKXr4UAX5Xk9ureHIMWNHBNfnqNl82tGmW/rDHSaN2N54F8am/YKsh3xJIvE8sXCWBDAy50cXv9xMtBRDYOfiR6IUr9FmMiYUQ1kbAr1jZlmevldAFY+WfwMSmEoiIK0k7lHJ2+FObxfxFoGu0Z0Nwh2apvQtK8Vn/wQQOk0bd2a/+cK8XgxX0ita6Wa5oQtaC9Qyq81+aQO5cDytO3QpCLxrUvOXvOXalx3VXebdn7Kwxv8e4h/eBy9f5qzGdwNn0IbXtkjPrZrD4G9YuLmkzSs06Q97pxQjyycWbVgW9kHx1dJ/cza8NoYBci3cm0Y1/xFTzHSWE=
  region: us-east-1
  app: Homepage
  env: homepage-env
  on:
    repo: kenfehling/homepage
