language: node_js
node_js:
  - "6"
services:
  - docker
install:
  - docker pull kenfehling/node6:latest
  - npm install --silent --progress false --color false
  - cd server; npm install --silent --progress false --color false; npm run build; cd ..
script:
  - docker run --name dc kenfehling/node6:latest &
  - sleep 5
  - docker cp server/* dc:/opt/server
  - docker exec -it dc "cd /opt/server; npm test"