language: node_js
node_js:
  - "6"
services:
  - docker
install:
  - docker pull kenfehling/node6
  - npm install
  - cd server; npm install; npm run build; cd ..
  - docker cp server kenfehling/node6:/opt
script:
  - docker run kenfehling/node6 -c "cd /opt/server; npm test"