language: node_js
node_js:
  - "6"
services:
  - docker
install:
  - docker pull kenfehling/node6:latest
  - npm install
  - cd server; npm install; npm run build; cd ..
  - docker cp server kenfehling/node6:latest:/opt
script:
  - docker run kenfehling/node6:latest -c "cd /opt/server; npm test"