language: node_js
node_js:
- '6'
services:
- docker
install:
- docker pull kenfehling/node6:latest
- npm install --depth 0
- cd server; npm install --depth 0; npm run build; cd ..
script:
- docker run --name dc kenfehling/node6:latest & sleep 1
- docker cp server dc:.
- docker exec dc bash -c "cd server; npm test"
before_deploy:
- zip -qr server.zip server -x server/node_modules
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIZDY5R5EQD3JXFJA
  secret_access_key:
    secure: dpF+kRF0bxlKdMhRuuKBTd7ShAbSdlKlzicjmYx6bmC4O1mVQmslVBQKsTUsmCc6hseul+PzOg2x+oS7uL2nvGzStH/HSuAsqpw1OKx+PG6Q7sid9z2iImpyJgcwpXiDNkJMIgcDhDkpNm2QLMYdSbWnML/mfp95UqVmmOCvufYHyqGz7D8wCCsFxT4051E5DRhoNG55HhUpqqqYFtfLCNCAj8D0q/g8sMJKgnww7DhqUN+1hUwuaHLmntciRNSTdUNPIMIMLHJBp4hL6WQlme/pIhcC4L61EJT0FowggbTYPsLSAeEo1lDKS43cllAtvgBihIDD8zoC+dRCwZM1jzlUY1LnErEpUKyv+//ApIfB1LKd0GqTvg7XaHsI/RSXRNJPEf9rOnc5AN8q/Tqi3YS1jSfuUGx1WOqSG1mZiARBnnxFFRVZsMsxjFrFbezov/IdIQEJg8cTUuSAz6K+yiEhaOZqEiN6C0ImTNyZI/jcNvVsGMWXHMa3Kh9yLZ2GBoAoomzGtduPiudCXXauIqNRGszH0WKHLzrTKdx/dMoDTt03PATZ1ozxgr4h1ubfAK+4XQXi16ddr8bcMN5E/uri1S8pEV48NAZCI0Qv7PwTCH54RJzHS9zUoqFUVsNJxxESphEdLaPWsX1LsUUEPnq8ghG9lki+pYrXEWy2sRA=
  region: us-east-1
  app: Homepage
  env: homepage-env
  bucket_name: kenfehling
  skip_cleanup: true
  zip_file: server.zip