version: '3'
services:
  web:
    image: kenfehling/homepage
    ports:
    - "3000:3000"
  ssl:
    image: valian/docker-nginx-auto-ssl
    ports:
      - "80:80"
    environment:
      SITES: '*.kenfehling.com=localhost:3000'